### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by derekqq** [stimulus-components/stimulus-popover#10]
Hi @guillaumebriday, do you think about support for typescript for every component? Could you add some examples of how to set it right (tsconfig, tslint/eslint etc.)? I can help you with the development of this library because I'm using it in my project.

**Comment by guillaumebriday** [comment]
Hey @derekqq 

Thanks for the suggestion! I don’t know that much TS tbh. Why do you think we should add TS in this project? 

Is ES6 not enough powerful these days? 

Thanks in advance

**Comment by derekqq** [comment]
@guillaumebriday current version stimulus has support to Typescript when someone uses Stimulus JS with Typescript they can't use your plugin, because get error "unknown type" etc and is forced to add its own type to complicate the code. 
All we need is to configure tsconfig and add the appropriate types as in this thread https://github.com/hotwired/stimulus/issues/121

**Comment by guillaumebriday** [comment]
I just read this thread from Sam Stephenson https://twitter.com/sstephenson/status/1365863627912339457 and it looks very cool

I don't know TS that much yet but that would be a great opportunity to learn.

But I will need to change to toolchains before going into this.

I would like to switch from Snowpack to https://vitejs.dev too.

I will try it asap

**Comment by guillaumebriday** [comment]
Ok I started with another controller to try. Here is the PR: https://github.com/stimulus-components/stimulus-timeago/pull/6

**Comment by guillaumebriday** [comment]
Maybe you could take a look @derekqq and I will do it the same on every single others

**Comment by derekqq** [comment]
@guillaumebriday sorry for the too late reply. Good idea with snowpack and vitejs. I reviewed your merge request.

**Comment by guillaumebriday** [comment]
fixed here https://github.com/stimulus-components/stimulus-popover/commit/9fb54cf9966d8e383bd21283bfd7ac307b46e331
