### ISSUE TITLE
Working w/ Image 

### ISSUE THREAD

**Issue by apsylone** [stimulus-components/stimulus-popover#11]
Hello, 

It seems the library doesn't work with image.
I've tried this : 
`<a href="#" class="relative block" data-action="mouseover->popover#show mouseout->popover#hide"><img src="..."></a>`

But it doesn't work.

**Comment by guillaumebriday** [comment]
Hum

You need to use AJAX or a template, please check https://stimulus-components.netlify.app/docs/components/stimulus-popover/#usage

The content in your `<a>` is not used at all by this package

**Comment by apsylone** [comment]
I would liked to popover on the `<img>` element instead of the `<a>`.
Your example works with text inside the `<a>` but not with other html tags.
Could you maybe give me an example of making my case working ?

**Comment by guillaumebriday** [comment]
Based on https://stimulus-components.netlify.app/docs/components/stimulus-popover/#with-local-template

```html
<div data-controller="popover">
  <img
    src="...."
    data-action="mouseover->popover#show mouseout->popover#hide"
  />

  <template data-popover-target="content">
    <div data-popover-target="card">
      <p>This content is in a hidden template.</p>
    </div>
  </template>
</div>
```

Should do the trick, can you confirm?

**Comment by apsylone** [comment]
Nope. The template is inserted into the <img> tag. That is weird.

**Comment by guillaumebriday** [comment]
ah got it. I use `appendChild` but it does not make any sense on img.

I released https://github.com/stimulus-components/stimulus-popover/releases/tag/v5.0.1 so you can use wrap your `img` in a not autoclosing tag.

Just tried in development and it works fine!

Let me know if it's good for you?

**Comment by guillaumebriday** [comment]
Feel free to repoen if you still have the issue @apsylone 👍
