### ISSUE TITLE
stimulus new version 3.0 is not compatible

### ISSUE THREAD

**Issue by jicheng1014** [stimulus-components/stimulus-popover#12]
`import { Controller } from 'stimulus'`  doesn't work when user install stimulus from `@hotwired/stimulus`

**Comment by Sybio** [comment]
Same here

**Comment by guillaumebriday** [comment]
I would like to fix a bug at this line https://github.com/stimulus-components/stimulus-popover/blob/master/src/index.ts#L30 with the `currentTarget` vs `target` before release a new version with Stimulus 3

**Comment by AlexKovynev** [comment]
@guillaumebriday Maybe it is time to release version for stimulus 3?:)

**Comment by ChechkovEugene** [comment]
The same. Voting for stimulus 3 :)

**Comment by kluzny** [comment]
@guillaumebriday Would you be willing to outline the bug in a test or an issue? Its not obvious to me what the problem is and if it is holding up https://github.com/stimulus-components/stimulus-popover/pull/14 it would be nice to finally advance support to hotwire.

**Comment by guillaumebriday** [comment]
Released in https://github.com/stimulus-components/stimulus-popover/releases/tag/v6.0.0

And the `currentTarget` has been fixed in https://github.com/stimulus-components/stimulus-popover/releases/tag/v6.1.0

Enjoy! 🎉
