### ISSUE TITLE
Webpacker failing to compile

### ISSUE THREAD

**Issue by bschrag620** [stimulus-components/stimulus-popover#19]
I'm trying to add `stimulus-popover` into an existing application and when doing so I'm unable to get webpacker to compile without an error. 
The specific error I'm seeing is:
```
ERROR in ./node_modules/stimulus-popover/dist/stimulus-popover.mjs 116:2-3
Can't import the named export 'Controller' from non EcmaScript module (only default export is available)
```
The project is using `@rails/webpacker:5.4.4` and `@hotwired/stimulus:3.2.1`. Any help here would be greatly appreciated!

**Comment by guillaumebriday** [comment]
Can you show me how you're trying to import it?

**Comment by bschrag620** [comment]
@guillaumebriday let me know if you need more info. Thanks for you help!

In `package.json` I have:
```
"stimulus-popover": "^6.2.0",
```

The `index.js` looks something like this:
```
import { Application } from "@hotwired/stimulus";
import { definitionsFromContext } from "@hotwired/stimulus-webpack-helpers";
import Popover from 'stimulus-popover'
window.Stimulus = Application.start();
window.Stimulus.register('popover', Popover)
const context = require.context("./controllers", true, /\.js$/);
Stimulus.load(definitionsFromContext(context));
```

When compiling, webpacker is throwing:
```
ERROR in ./node_modules/stimulus-popover/dist/stimulus-popover.mjs 116:2-3
Can't import the named export 'Controller' from non EcmaScript module (only default export is available)
```

**Comment by guillaumebriday** [comment]
If you still have the issue, please reopen an issue in the main monorepo: https://github.com/stimulus-components/stimulus-components
