### ISSUE TITLE
README.md maybe using wrong methods (mouseOver/mouseOut)

### ISSUE THREAD

**Issue by alispat** [stimulus-components/stimulus-popover#6]
In **README.md**, I guess it should be:

`mouseover->popover#show mouseout->popover#hide`

and not:

`mouseover->popover#mouseOver mouseout->popover#mouseOut`

**Comment by guillaumebriday** [comment]
Nice catch

Fixed here https://github.com/stimulus-components/stimulus-popover/commit/c595de1ca9fdc985f925baeb94206eefcfa01d08

Thanks @alispat

**Comment by guillaumebriday** [comment]
Do not hesitate to open PR, that would be awesome! 👍
